version: '3.8'
services:
      fe:
            command: npm start
            ports:
                  - 3000:3000
            build: ./client
      be:
            command: node index.js
            ports:
                  - 8000:8000
            build: ./server
            environment:
                  - PORT=8000
                  - MONGODBURL=mongodb://db:27017/mydatabase
      db:
            image: mongo
            ports:
                  - 27017:27017
            volumes:
                  - merndata:/data/db
volumes:
      merndata: