version: '3.8'
services:
      fe:
            command: npm start
            ports:
                  - 3000:3000
            build: ./client
      be:
            command: node app.js
            ports:
                  - 8080:8080
            build: ./
      db:
            image: mongo
            ports:
                  - 27017:27017
            volumes:
                  - merndata:/var/lib
volumes:
      merndata: